export const COMPANY_TYPES = [
	{ value: "Product provider", label: "Product provider" },
	{ value: "Service provider", label: "Service provider" },
	{ value: "Product & Service provider", label: "Product & Service provider" }
];

export const N_EMPOYEES = [
	{ value: 0, label: "No limit" },
	{ value: 1, label: "3" },
	{ value: 2, label: "8" },
	{ value: 3, label: "15" },
	{ value: 4, label: "30" },
	{ value: 5, label: "50" },
	{ value: 6, label: "80" },
	{ value: 7, label: "120" },
	{ value: 8, label: "200" },
	{ value: 9, label: "400" },
	{ value: 10, label: "1000" },
	{ value: 11, label: "3000" },
	{ value: 12, label: "10000" }
];

export const REVENUES = [
	{ value: 0, label: "No limit" },
	{ value: 1, label: "0" },
	{ value: 2, label: "500K" },
	{ value: 3, label: "1M" },
	{ value: 4, label: "2M" },
	{ value: 5, label: "4M" },
	{ value: 6, label: "8M" },
	{ value: 7, label: "15M" },
	{ value: 8, label: "30M" },
	{ value: 9, label: "60M" },
	{ value: 10, label: "100M" },
	{ value: 11, label: "150M" },
	{ value: 12, label: "300M" }
];

export const ATECO_CODES = [
	{ value: "24.1", label: "24.1" },
	{ value: "24.2", label: "24.2" },
	{ value: "24.31", label: "24.31" },
	{ value: "24.32", label: "24.32" },
	{ value: "24.33", label: "24.33" },
	{ value: "24.34", label: "24.34" },
	{ value: "24.41", label: "24.41" },
	{ value: "24.42", label: "24.42" },
	{ value: "24.43", label: "24.43" },
	{ value: "24.44", label: "24.44" },
	{ value: "24.45", label: "24.45" },
	{ value: "24.51", label: "24.51" },
	{ value: "24.52", label: "24.52" },
	{ value: "24.53", label: "24.53" },
	{ value: "24.54", label: "24.54" },
	{ value: "25.11", label: "25.11" },
	{ value: "25.12.1", label: "25.12.1" },
	{ value: "25.21", label: "25.21" },
	{ value: "25.29", label: "25.29" },
	{ value: "25.3", label: "25.3" },
	{ value: "25.5", label: "25.5" },
	{ value: "25.61", label: "25.61" },
	{ value: "25.62", label: "25.62" },
	{ value: "25.7", label: "25.7" },
	{ value: "25.9", label: "25.9" },
	{ value: "26.12", label: "26.12" },
	{ value: "26.2", label: "26.2" },
	{ value: "26.30.1", label: "26.30.1" },
	{ value: "26.51.10", label: "26.51.10" },
	{ value: "26.52", label: "26.52" },
	{ value: "26.70.11", label: "26.70.11" },
	{ value: "28 (tutti/all)", label: "28 (tutti/all)" },
	{ value: "29.1", label: "29.1" },
	{ value: "29.2", label: "29.2" },
	{ value: "29.3", label: "29.3" },
	{ value: "33.11", label: "33.11" },
	{ value: "33.2", label: "33.2" },
	{ value: "46.61", label: "46.61" },
	{ value: "46.62", label: "46.62" },
	{ value: "46.63", label: "46.63" },
	{ value: "46.64", label: "46.64" },
	{ value: "46.69.20", label: "46.69.20" },
	{ value: "46.69.91", label: "46.69.91" },
	{ value: "46.69.94", label: "46.69.94" },
	{ value: "46.69.99", label: "46.69.99" }
];

export const REGIONS = [
	{ value: "1", label: "Abruzzo" },
	{ value: "2", label: "Basilicata" },
	{ value: "3", label: "Calabria" },
	{ value: "4", label: "Campania" },
	{ value: "5", label: "Emilia Romagna" },
	{ value: "6", label: "Friuli-Venezia Giulia" },
	{ value: "7", label: "Lazio" },
	{ value: "8", label: "Liguria" },
	{ value: "9", label: "Lombardia" },
	{ value: "10", label: "Marche" },
	{ value: "11", label: "Molise" },
	{ value: "12", label: "Piemonte" },
	{ value: "13", label: "Puglia" },
	{ value: "14", label: "Sardegna" },
	{ value: "15", label: "Sicilia" },
	{ value: "16", label: "Trentino-Alto Adige" },
	{ value: "17", label: "Toscana" },
	{ value: "18", label: "Umbria" },
	{ value: "19", label: "Valle d'Aosta" },
	{ value: "20", label: "Veneto" }
];

// export const CITIES = [
// 	{ value: "Chieti", label: "Chieti" },
// 	{ value: "L'Aquila", label: "L'Aquila" },
// 	{ value: "Pescara", label: "Pescara" },
// 	{ value: "Teramo", label: "Teramo" },
// 	{ value: "Matera", label: "Matera" },
// 	{ value: "Potenza", label: "Potenza" },
// 	{ value: "Catanzaro", label: "Catanzaro" },
// 	{ value: "Cosenza", label: "Cosenza" },
// 	{ value: "Crotone", label: "Crotone" },
// 	{ value: "Reggio Calabria", label: "Reggio Calabria" },
// 	{ value: "Vibo Valentia", label: "Vibo Valentia" },
// 	{ value: "Avellino", label: "Avellino" },
// 	{ value: "Benevento", label: "Benevento" },
// 	{ value: "Caserta", label: "Caserta" },
// 	{ value: "Napoli", label: "Napoli" },
// 	{ value: "Salerno", label: "Salerno" },
// 	{ value: "Bologna", label: "Bologna" },
// 	{ value: "Cesena", label: "Cesena" },
// 	{ value: "Ferrara", label: "Ferrara" },
// 	{ value: "Forlì", label: "Forlì" },
// 	{ value: "Modena", label: "Modena" },
// 	{ value: "Parma", label: "Parma" },
// 	{ value: "Piacenza", label: "Piacenza" },
// 	{ value: "Ravenna", label: "Ravenna" },
// 	{ value: "Reggio Emilia", label: "Reggio Emilia" },
// 	{ value: "Rimini", label: "Rimini" },
// 	{ value: "Gorizia", label: "Gorizia" },
// 	{ value: "Pordenone", label: "Pordenone" },
// 	{ value: "Trieste", label: "Trieste" },
// 	{ value: "Udine", label: "Udine" },
// 	{ value: "Frosinone", label: "Frosinone" },
// 	{ value: "Latina", label: "Latina" },
// 	{ value: "Rieti", label: "Rieti" },
// 	{ value: "Roma", label: "Roma" },
// 	{ value: "Viterbo", label: "Viterbo" },
// 	{ value: "Genova", label: "Genova" },
// 	{ value: "Imperia", label: "Imperia" },
// 	{ value: "La Spezia", label: "La Spezia" },
// 	{ value: "Savona", label: "Savona" },
// 	{ value: "Bergamo", label: "Bergamo" },
// 	{ value: "Brescia", label: "Brescia" },
// 	{ value: "Como", label: "Como" },
// 	{ value: "Cremona", label: "Cremona" },
// 	{ value: "Lecco", label: "Lecco" },
// 	{ value: "Lodi", label: "Lodi" },
// 	{ value: "Mantova", label: "Mantova" },
// 	{ value: "Milano", label: "Milano" },
// 	{ value: "Monza", label: "Monza" },
// 	{ value: "Pavia", label: "Pavia" },
// 	{ value: "Sondrio", label: "Sondrio" },
// 	{ value: "Varese", label: "Varese" },
// 	{ value: "Ancona", label: "Ancona" },
// 	{ value: "Ascoli Piceno", label: "Ascoli Piceno" },
// 	{ value: "Fermo", label: "Fermo" },
// 	{ value: "Macerata", label: "Macerata" },
// 	{ value: "Pesaro", label: "Pesaro" },
// 	{ value: "Urbino", label: "Urbino" },
// 	{ value: "Campobasso", label: "Campobasso" },
// 	{ value: "Isernia", label: "Isernia" },
// 	{ value: "Alessandria", label: "Alessandria" },
// 	{ value: "Asti", label: "Asti" },
// 	{ value: "Biella", label: "Biella" },
// 	{ value: "Cuneo", label: "Cuneo" },
// 	{ value: "Novara", label: "Novara" },
// 	{ value: "Torino", label: "Torino" },
// 	{ value: "Verbania", label: "Verbania" },
// 	{ value: "Vercelli", label: "Vercelli" },
// 	{ value: "Andria", label: "Andria" },
// 	{ value: "Bari", label: "Bari" },
// 	{ value: "Barletta", label: "Barletta" },
// 	{ value: "Brindisi", label: "Brindisi" },
// 	{ value: "Foggia", label: "Foggia" },
// 	{ value: "Lecce", label: "Lecce" },
// 	{ value: "Taranto", label: "Taranto" },
// 	{ value: "Trani", label: "Trani" },
// 	{ value: "Cagliari", label: "Cagliari" },
// 	{ value: "Carbonia", label: "Carbonia" },
// 	{ value: "Nuoro", label: "Nuoro" },
// 	{ value: "Oristano", label: "Oristano" },
// 	{ value: "Sassari", label: "Sassari" },
// 	{ value: "Agrigento", label: "Agrigento" },
// 	{ value: "Caltanissetta", label: "Caltanissetta" },
// 	{ value: "Catania", label: "Catania" },
// 	{ value: "Enna", label: "Enna" },
// 	{ value: "Messina", label: "Messina" },
// 	{ value: "Palermo", label: "Palermo" },
// 	{ value: "Ragusa", label: "Ragusa" },
// 	{ value: "Siracusa", label: "Siracusa" },
// 	{ value: "Trapani", label: "Trapani" },
// 	{ value: "Bolzano", label: "Bolzano" },
// 	{ value: "Trento", label: "Trento" },
// 	{ value: "Arezzo", label: "Arezzo" },
// 	{ value: "Firenze", label: "Firenze" },
// 	{ value: "Grosseto", label: "Grosseto" },
// 	{ value: "Livorno", label: "Livorno" },
// 	{ value: "Lucca", label: "Lucca" },
// 	{ value: "Massa", label: "Massa" },
// 	{ value: "Pisa", label: "Pisa" },
// 	{ value: "Pistoia", label: "Pistoia" },
// 	{ value: "Prato", label: "Prato" },
// 	{ value: "Siena", label: "Siena" },
// 	{ value: "Perugia", label: "Perugia" },
// 	{ value: "Terni", label: "Terni" },
// 	{ value: "Aosta", label: "Aosta" },
// 	{ value: "Belluno", label: "Belluno" },
// 	{ value: "Padova", label: "Padova" },
// 	{ value: "Rovigo", label: "Rovigo" },
// 	{ value: "Treviso", label: "Treviso" },
// 	{ value: "Venezia", label: "Venezia" },
// 	{ value: "Verona", label: "Verona" },
// 	{ value: "Vicenza", label: "Vicenza" }
// ];

export const CITIES = [
	{ value: "1", label: "Chieti" },
	{ value: "2", label: "L'Aquila" },
	{ value: "3", label: "Pescara" },
	{ value: "4", label: "Teramo" },
	{ value: "5", label: "Matera" },
	{ value: "6", label: "Potenza" },
	{ value: "7", label: "Catanzaro" },
	{ value: "8", label: "Cosenza" },
	{ value: "9", label: "Crotone" },
	{ value: "10", label: "Reggio Calabria" },
	{ value: "11", label: "Vibo Valentia" },
	{ value: "12", label: "Avellino" },
	{ value: "13", label: "Benevento" },
	{ value: "14", label: "Caserta" },
	{ value: "15", label: "Napoli" },
	{ value: "16", label: "Salerno" },
	{ value: "17", label: "Bologna" },
	{ value: "18", label: "Cesena" },
	{ value: "19", label: "Ferrara" },
	{ value: "20", label: "Forlì" },
	{ value: "21", label: "Modena" },
	{ value: "22", label: "Parma" },
	{ value: "23", label: "Piacenza" },
	{ value: "24", label: "Ravenna" },
	{ value: "25", label: "Reggio Emilia" },
	{ value: "26", label: "Rimini" },
	{ value: "27", label: "Gorizia" },
	{ value: "28", label: "Pordenone" },
	{ value: "29", label: "Trieste" },
	{ value: "30", label: "Udine" },
	{ value: "31", label: "Frosinone" },
	{ value: "32", label: "Latina" },
	{ value: "33", label: "Rieti" },
	{ value: "34", label: "Roma" },
	{ value: "35", label: "Viterbo" },
	{ value: "36", label: "Genova" },
	{ value: "37", label: "Imperia" },
	{ value: "38", label: "La Spezia" },
	{ value: "39", label: "Savona" },
	{ value: "40", label: "Bergamo" },
	{ value: "41", label: "Brescia" },
	{ value: "42", label: "Como" },
	{ value: "43", label: "Cremona" },
	{ value: "44", label: "Lecco" },
	{ value: "45", label: "Lodi" },
	{ value: "46", label: "Mantova" },
	{ value: "47", label: "Milano" },
	{ value: "48", label: "Monza" },
	{ value: "49", label: "Pavia" },
	{ value: "50", label: "Sondrio" },
	{ value: "51", label: "Varese" },
	{ value: "52", label: "Ancona" },
	{ value: "53", label: "Ascoli Piceno" },
	{ value: "54", label: "Fermo" },
	{ value: "55", label: "Macerata" },
	{ value: "56", label: "Pesaro" },
	{ value: "57", label: "Urbino" },
	{ value: "58", label: "Campobasso" },
	{ value: "59", label: "Isernia" },
	{ value: "60", label: "Alessandria" },
	{ value: "61", label: "Asti" },
	{ value: "62", label: "Biella" },
	{ value: "63", label: "Cuneo" },
	{ value: "64", label: "Novara" },
	{ value: "65", label: "Torino" },
	{ value: "66", label: "Verbania" },
	{ value: "67", label: "Vercelli" },
	{ value: "68", label: "Andria" },
	{ value: "69", label: "Bari" },
	{ value: "70", label: "Barletta" },
	{ value: "71", label: "Brindisi" },
	{ value: "72", label: "Foggia" },
	{ value: "73", label: "Lecce" },
	{ value: "74", label: "Taranto" },
	{ value: "75", label: "Trani" },
	{ value: "76", label: "Cagliari" },
	{ value: "77", label: "Carbonia" },
	{ value: "78", label: "Nuoro" },
	{ value: "79", label: "Oristano" },
	{ value: "80", label: "Sassari" },
	{ value: "81", label: "Agrigento" },
	{ value: "82", label: "Caltanissetta" },
	{ value: "83", label: "Catania" },
	{ value: "84", label: "Enna" },
	{ value: "85", label: "Messina" },
	{ value: "86", label: "Palermo" },
	{ value: "87", label: "Ragusa" },
	{ value: "88", label: "Siracusa" },
	{ value: "89", label: "Trapani" },
	{ value: "90", label: "Bolzano" },
	{ value: "91", label: "Trento" },
	{ value: "92", label: "Arezzo" },
	{ value: "93", label: "Firenze" },
	{ value: "94", label: "Grosseto" },
	{ value: "95", label: "Livorno" },
	{ value: "96", label: "Lucca" },
	{ value: "97", label: "Massa" },
	{ value: "98", label: "Pisa" },
	{ value: "99", label: "Pistoia" },
	{ value: "100", label: "Prato" },
	{ value: "101", label: "Siena" },
	{ value: "102", label: "Perugia" },
	{ value: "103", label: "Terni" },
	{ value: "104", label: "Aosta" },
	{ value: "105", label: "Belluno" },
	{ value: "106", label: "Padova" },
	{ value: "107", label: "Rovigo" },
	{ value: "108", label: "Treviso" },
	{ value: "109", label: "Venezia" },
	{ value: "110", label: "Verona" },
	{ value: "111", label: "Vicenza" }
];

export const CITIES_WITH_REGIONS = [
	{ value: "1", label: "Chieti", region: "1" },
	{ value: "2", label: "L'Aquila", region: "1" },
	{ value: "3", label: "Pescara", region: "1" },
	{ value: "4", label: "Teramo", region: "1" },
	{ value: "5", label: "Matera", region: "2" },
	{ value: "6", label: "Potenza", region: "2" },
	{ value: "7", label: "Catanzaro", region: "3" },
	{ value: "8", label: "Cosenza", region: "3" },
	{ value: "9", label: "Crotone", region: "3" },
	{ value: "10", label: "Reggio Calabria", region: "3" },
	{ value: "11", label: "Vibo Valentia", region: "3" },
	{ value: "12", label: "Avellino", region: "4" },
	{ value: "13", label: "Benevento", region: "4" },
	{ value: "14", label: "Caserta", region: "4" },
	{ value: "15", label: "Napoli", region: "4" },
	{ value: "16", label: "Salerno", region: "4" },
	{ value: "17", label: "Bologna", region: "5" },
	{ value: "18", label: "Cesena", region: "5" },
	{ value: "19", label: "Ferrara", region: "5" },
	{ value: "20", label: "Forlì", region: "5" },
	{ value: "21", label: "Modena", region: "5" },
	{ value: "22", label: "Parma", region: "5" },
	{ value: "23", label: "Piacenza", region: "5" },
	{ value: "24", label: "Ravenna", region: "5" },
	{ value: "25", label: "Reggio Emilia", region: "5" },
	{ value: "26", label: "Rimini", region: "5" },
	{ value: "27", label: "Gorizia", region: "6" },
	{ value: "28", label: "Pordenone", region: "6" },
	{ value: "29", label: "Trieste", region: "6" },
	{ value: "30", label: "Udine", region: "6" },
	{ value: "31", label: "Frosinone", region: "7" },
	{ value: "32", label: "Latina", region: "7" },
	{ value: "33", label: "Rieti", region: "7" },
	{ value: "34", label: "Roma", region: "7" },
	{ value: "35", label: "Viterbo", region: "7" },
	{ value: "36", label: "Genova", region: "8" },
	{ value: "37", label: "Imperia", region: "8" },
	{ value: "38", label: "La Spezia", region: "8" },
	{ value: "39", label: "Savona", region: "9" },
	{ value: "40", label: "Bergamo", region: "9" },
	{ value: "41", label: "Brescia", region: "9" },
	{ value: "42", label: "Como", region: "9" },
	{ value: "43", label: "Cremona", region: "9" },
	{ value: "44", label: "Lecco", region: "9" },
	{ value: "45", label: "Lodi", region: "9" },
	{ value: "46", label: "Mantova", region: "9" },
	{ value: "47", label: "Milano", region: "9" },
	{ value: "48", label: "Monza", region: "9" },
	{ value: "49", label: "Pavia", region: "9" },
	{ value: "50", label: "Sondrio", region: "9" },
	{ value: "51", label: "Varese", region: "9" },
	{ value: "52", label: "Ancona", region: "10" },
	{ value: "53", label: "Ascoli Piceno", region: "10" },
	{ value: "54", label: "Fermo", region: "10" },
	{ value: "55", label: "Macerata", region: "10" },
	{ value: "56", label: "Pesaro", region: "10" },
	{ value: "57", label: "Urbino", region: "10" },
	{ value: "58", label: "Campobasso", region: "11" },
	{ value: "59", label: "Isernia", region: "11" },
	{ value: "60", label: "Alessandria", region: "12" },
	{ value: "61", label: "Asti", region: "12" },
	{ value: "62", label: "Biella", region: "12" },
	{ value: "63", label: "Cuneo", region: "12" },
	{ value: "64", label: "Novara", region: "12" },
	{ value: "65", label: "Torino", region: "12" },
	{ value: "66", label: "Verbania", region: "12" },
	{ value: "67", label: "Vercelli", region: "12" },
	{ value: "68", label: "Andria", region: "13" },
	{ value: "69", label: "Bari", region: "13" },
	{ value: "70", label: "Barletta", region: "13" },
	{ value: "71", label: "Brindisi", region: "13" },
	{ value: "72", label: "Foggia", region: "13" },
	{ value: "73", label: "Lecce", region: "13" },
	{ value: "74", label: "Taranto", region: "13" },
	{ value: "75", label: "Trani", region: "13" },
	{ value: "76", label: "Cagliari", region: "14" },
	{ value: "77", label: "Carbonia", region: "14" },
	{ value: "78", label: "Nuoro", region: "14" },
	{ value: "79", label: "Oristano", region: "14" },
	{ value: "80", label: "Sassari", region: "14" },
	{ value: "81", label: "Agrigento", region: "15" },
	{ value: "82", label: "Caltanissetta", region: "15" },
	{ value: "83", label: "Catania", region: "15" },
	{ value: "84", label: "Enna", region: "15" },
	{ value: "85", label: "Messina", region: "15" },
	{ value: "86", label: "Palermo", region: "15" },
	{ value: "87", label: "Ragusa", region: "15" },
	{ value: "88", label: "Siracusa", region: "15" },
	{ value: "89", label: "Trapani", region: "15" },
	{ value: "90", label: "Bolzano", region: "16" },
	{ value: "91", label: "Trento", region: "16" },
	{ value: "92", label: "Arezzo", region: "17" },
	{ value: "93", label: "Firenze", region: "17" },
	{ value: "94", label: "Grosseto", region: "17" },
	{ value: "95", label: "Livorno", region: "17" },
	{ value: "96", label: "Lucca", region: "17" },
	{ value: "97", label: "Massa", region: "17" },
	{ value: "98", label: "Pisa", region: "17" },
	{ value: "99", label: "Pistoia", region: "17" },
	{ value: "100", label: "Prato", region: "17" },
	{ value: "101", label: "Siena", region: "17" },
	{ value: "102", label: "Perugia", region: "18" },
	{ value: "103", label: "Terni", region: "18" },
	{ value: "104", label: "Aosta", region: "19" },
	{ value: "105", label: "Belluno", region: "20" },
	{ value: "106", label: "Padova", region: "20" },
	{ value: "107", label: "Rovigo", region: "20" },
	{ value: "108", label: "Treviso", region: "20" },
	{ value: "109", label: "Venezia", region: "20" },
	{ value: "110", label: "Verona", region: "20" },
	{ value: "111", label: "Vicenza", region: "20" }
];

export const citiesInRegion = regionId => {
	let cities = [];
	for (let i in CITIES_WITH_REGIONS) {
		if (regionId === CITIES_WITH_REGIONS[i].region) {
			cities.push(CITIES_WITH_REGIONS[i]);
		}
	}
	return cities;
};

export const maxsFromMin = (minId, items) => {
	let maxs = [];
	for (let i in items) {
		if (items[i].value > minId || items[i].value === 0) {
			maxs.push(items[i]);
		}
	}
	return maxs;
};

export const minsFromMax = (maxId, items) => {
	if (maxId === 0) {
		return items;
	}

	let mins = [];
	for (let i in items) {
		if (items[i].value < maxId || items[i].value === 0) {
			mins.push(items[i]);
		}
	}
	return mins;
};
